#!/usr/bin/env bash
set -eu # stop on error or undefined variables


# Interface: Run this script to open the codebase in Xcode.


###############################################################################
# Implementation:

cd "$( dirname "${BASH_SOURCE[0]}" )"  # Change into script directory so it can be run from anywhere.

# Generates Xcode project and opens it.
# Output: The generated project is written into the Tulsi output base.
    # This avoids adding generated, working state to the source tree. Originally promted by discussion here https://github.com/bazelbuild/tulsi/pull/255#issuecomment-966031834
# We also detect and supply the bazel command to Tulsi, because Tulsi seems to have trouble autodetecting bazel when run from the command line in some (but not all) cases. So "--bazel "$(command -v bazel)" just autodetects it from the path.
#   In particular, the problem seems to happen before a tulsiconf-user cache had been generated by the Tulsi GUI (on project save). That leads to the following error: "Failed to read the given generator config: Config file at /Users/sredmond-hedron/Developer/Hedron/Product/XcodeAdapter/XcodeAdapter.tulsiproj/Configs/Main.tulsigen is invalid: Unable to find Bazel Path"
bazel run @build_bazel_tulsi//:tulsi -- -- --genconfig {{wherever}}.tulsiproj:Main --outputfolder "$(bazel info output_base)" --bazel "$(command -v bazel)"
