//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: Kaly2iOS/Shared/logic/Infrastructure/Impl/Protos/MapService.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `Ca_Joelathiessen_Kaly2_Proto_MapServiceClient`, then call methods of this protocol to make API calls.
internal protocol Ca_Joelathiessen_Kaly2_Proto_MapServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Ca_Joelathiessen_Kaly2_Proto_MapServiceClientInterceptorFactoryProtocol? { get }

  func createMap(
    _ request: Ca_Joelathiessen_Kaly2_Proto_CreateMapRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Ca_Joelathiessen_Kaly2_Proto_CreateMapRequest, Ca_Joelathiessen_Kaly2_Proto_CreateMapResponse>
}

extension Ca_Joelathiessen_Kaly2_Proto_MapServiceClientProtocol {
  internal var serviceName: String {
    return "ca.joelathiessen.kaly2.proto.MapService"
  }

  /// Unary call to CreateMap
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateMap.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func createMap(
    _ request: Ca_Joelathiessen_Kaly2_Proto_CreateMapRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Ca_Joelathiessen_Kaly2_Proto_CreateMapRequest, Ca_Joelathiessen_Kaly2_Proto_CreateMapResponse> {
    return self.makeUnaryCall(
      path: Ca_Joelathiessen_Kaly2_Proto_MapServiceClientMetadata.Methods.createMap.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateMapInterceptors() ?? []
    )
  }
}

internal final class Ca_Joelathiessen_Kaly2_Proto_MapServiceClient: Ca_Joelathiessen_Kaly2_Proto_MapServiceClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Ca_Joelathiessen_Kaly2_Proto_MapServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the ca.joelathiessen.kaly2.proto.MapService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Ca_Joelathiessen_Kaly2_Proto_MapServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#if compiler(>=5.5) && canImport(_Concurrency)
@available(macOS 12, iOS 15, tvOS 15, watchOS 8, *)
internal protocol Ca_Joelathiessen_Kaly2_Proto_MapServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Ca_Joelathiessen_Kaly2_Proto_MapServiceClientInterceptorFactoryProtocol? { get }

  func makeCreateMapCall(
    _ request: Ca_Joelathiessen_Kaly2_Proto_CreateMapRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Ca_Joelathiessen_Kaly2_Proto_CreateMapRequest, Ca_Joelathiessen_Kaly2_Proto_CreateMapResponse>
}

@available(macOS 12, iOS 15, tvOS 15, watchOS 8, *)
extension Ca_Joelathiessen_Kaly2_Proto_MapServiceAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Ca_Joelathiessen_Kaly2_Proto_MapServiceClientMetadata.serviceDescriptor
  }

  internal var interceptors: Ca_Joelathiessen_Kaly2_Proto_MapServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeCreateMapCall(
    _ request: Ca_Joelathiessen_Kaly2_Proto_CreateMapRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Ca_Joelathiessen_Kaly2_Proto_CreateMapRequest, Ca_Joelathiessen_Kaly2_Proto_CreateMapResponse> {
    return self.makeAsyncUnaryCall(
      path: Ca_Joelathiessen_Kaly2_Proto_MapServiceClientMetadata.Methods.createMap.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateMapInterceptors() ?? []
    )
  }
}

@available(macOS 12, iOS 15, tvOS 15, watchOS 8, *)
extension Ca_Joelathiessen_Kaly2_Proto_MapServiceAsyncClientProtocol {
  internal func createMap(
    _ request: Ca_Joelathiessen_Kaly2_Proto_CreateMapRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Ca_Joelathiessen_Kaly2_Proto_CreateMapResponse {
    return try await self.performAsyncUnaryCall(
      path: Ca_Joelathiessen_Kaly2_Proto_MapServiceClientMetadata.Methods.createMap.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateMapInterceptors() ?? []
    )
  }
}

@available(macOS 12, iOS 15, tvOS 15, watchOS 8, *)
internal struct Ca_Joelathiessen_Kaly2_Proto_MapServiceAsyncClient: Ca_Joelathiessen_Kaly2_Proto_MapServiceAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Ca_Joelathiessen_Kaly2_Proto_MapServiceClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Ca_Joelathiessen_Kaly2_Proto_MapServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#endif // compiler(>=5.5) && canImport(_Concurrency)

internal protocol Ca_Joelathiessen_Kaly2_Proto_MapServiceClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'createMap'.
  func makeCreateMapInterceptors() -> [ClientInterceptor<Ca_Joelathiessen_Kaly2_Proto_CreateMapRequest, Ca_Joelathiessen_Kaly2_Proto_CreateMapResponse>]
}

internal enum Ca_Joelathiessen_Kaly2_Proto_MapServiceClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "MapService",
    fullName: "ca.joelathiessen.kaly2.proto.MapService",
    methods: [
      Ca_Joelathiessen_Kaly2_Proto_MapServiceClientMetadata.Methods.createMap,
    ]
  )

  internal enum Methods {
    internal static let createMap = GRPCMethodDescriptor(
      name: "CreateMap",
      path: "/ca.joelathiessen.kaly2.proto.MapService/CreateMap",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Ca_Joelathiessen_Kaly2_Proto_MapServiceProvider: CallHandlerProvider {
  var interceptors: Ca_Joelathiessen_Kaly2_Proto_MapServiceServerInterceptorFactoryProtocol? { get }

  func createMap(request: Ca_Joelathiessen_Kaly2_Proto_CreateMapRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Ca_Joelathiessen_Kaly2_Proto_CreateMapResponse>
}

extension Ca_Joelathiessen_Kaly2_Proto_MapServiceProvider {
  internal var serviceName: Substring {
    return Ca_Joelathiessen_Kaly2_Proto_MapServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "CreateMap":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Ca_Joelathiessen_Kaly2_Proto_CreateMapRequest>(),
        responseSerializer: ProtobufSerializer<Ca_Joelathiessen_Kaly2_Proto_CreateMapResponse>(),
        interceptors: self.interceptors?.makeCreateMapInterceptors() ?? [],
        userFunction: self.createMap(request:context:)
      )

    default:
      return nil
    }
  }
}

internal protocol Ca_Joelathiessen_Kaly2_Proto_MapServiceServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'createMap'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCreateMapInterceptors() -> [ServerInterceptor<Ca_Joelathiessen_Kaly2_Proto_CreateMapRequest, Ca_Joelathiessen_Kaly2_Proto_CreateMapResponse>]
}

internal enum Ca_Joelathiessen_Kaly2_Proto_MapServiceServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "MapService",
    fullName: "ca.joelathiessen.kaly2.proto.MapService",
    methods: [
      Ca_Joelathiessen_Kaly2_Proto_MapServiceServerMetadata.Methods.createMap,
    ]
  )

  internal enum Methods {
    internal static let createMap = GRPCMethodDescriptor(
      name: "CreateMap",
      path: "/ca.joelathiessen.kaly2.proto.MapService/CreateMap",
      type: GRPCCallType.unary
    )
  }
}
