name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: macos-11
    steps:
    - name: Choose Xcode
      run: sudo xcode-select -s /Applications/Xcode_13.2.1.app
    - name: Setup Bazel cache
      uses: actions/cache@v2.1.4
      env:
        cache-name: bazel-cache
      with:
        path: |
          ~/.cache/bazelisk
          ~/.cache/bazel
          /private/var/tmp/_bazel_runner
          ~/.mint
        key: ${{ runner.os }}-${{ env.cache-name }}
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Lint
      run: ./lintformat.sh
    - name: Build for iOS
      run: ./build.sh --config ci
    - name: Run iOS tests
      run: ./test.sh --config ci